# Decision Tree, Random Forest Classifier, Gradient Boost

In [1]:
import findspark
findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("DataFrame").config("spark.sql.repl.eagerEval.enabled", True).getOrCreate()
spark

In [2]:
from pyspark.ml.classification import DecisionTreeClassifier, RandomForestClassifier, GBTClassifier
from pyspark.ml.feature import StringIndexer
from pyspark.ml.feature import OneHotEncoder
from pyspark.ml.feature import VectorAssembler

In [4]:
df = spark.read.csv("datasets/titanic.csv", header="true", inferSchema="true")
df.show(5)

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 5 rows

### Simple EDA

In [5]:
df.count()

891

In [6]:
len(df.columns)

12

In [7]:
df.printSchema()

root
 |-- PassengerId: integer (nullable = true)
 |-- Survived: integer (nullable = true)
 |-- Pclass: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: double (nullable = true)
 |-- SibSp: integer (nullable = true)
 |-- Parch: integer (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: double (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)

In [8]:
## 불필요한 column 삭제
df = df.drop("PassengerId", "Name", "Ticket", "Cabin")
df.show(5)

+--------+------+------+----+-----+-----+-------+--------+
|Survived|Pclass|   Sex| Age|SibSp|Parch|   Fare|Embarked|
+--------+------+------+----+-----+-----+-------+--------+
|       0|     3|  male|22.0|    1|    0|   7.25|       S|
|       1|     1|female|38.0|    1|    0|71.2833|       C|
|       1|     3|female|26.0|    0|    0|  7.925|       S|
|       1|     1|female|35.0|    1|    0|   53.1|       S|
|       0|     3|  male|35.0|    0|    0|   8.05|       S|
+--------+------+------+----+-----+-----+-------+--------+
only showing top 5 rows

In [9]:
df.show(100)

+--------+------+------+----+-----+-----+--------+--------+
|Survived|Pclass|   Sex| Age|SibSp|Parch|    Fare|Embarked|
+--------+------+------+----+-----+-----+--------+--------+
|       0|     3|  male|22.0|    1|    0|    7.25|       S|
|       1|     1|female|38.0|    1|    0| 71.2833|       C|
|       1|     3|female|26.0|    0|    0|   7.925|       S|
|       1|     1|female|35.0|    1|    0|    53.1|       S|
|       0|     3|  male|35.0|    0|    0|    8.05|       S|
|       0|     3|  male|null|    0|    0|  8.4583|       Q|
|       0|     1|  male|54.0|    0|    0| 51.8625|       S|
|       0|     3|  male| 2.0|    3|    1|  21.075|       S|
|       1|     3|female|27.0|    0|    2| 11.1333|       S|
|       1|     2|female|14.0|    1|    0| 30.0708|       C|
|       1|     3|female| 4.0|    1|    1|    16.7|       S|
|       1|     1|female|58.0|    0|    0|   26.55|       S|
|       0|     3|  male|20.0|    0|    0|    8.05|       S|
|       0|     3|  male|39.0|    1|    5|  31.275|       S|
|       0|     3|female|14.0|    0|    0|  7.8542|       S|
|       1|     2|female|55.0|    0|    0|    16.0|       S|
|       0|     3|  male| 2.0|    4|    1|  29.125|       Q|
|       1|     2|  male|null|    0|    0|    13.0|       S|
|       0|     3|female|31.0|    1|    0|    18.0|       S|
|       1|     3|female|null|    0|    0|   7.225|       C|
|       0|     2|  male|35.0|    0|    0|    26.0|       S|
|       1|     2|  male|34.0|    0|    0|    13.0|       S|
|       1|     3|female|15.0|    0|    0|  8.0292|       Q|
|       1|     1|  male|28.0|    0|    0|    35.5|       S|
|       0|     3|female| 8.0|    3|    1|  21.075|       S|
|       1|     3|female|38.0|    1|    5| 31.3875|       S|
|       0|     3|  male|null|    0|    0|   7.225|       C|
|       0|     1|  male|19.0|    3|    2|   263.0|       S|
|       1|     3|female|null|    0|    0|  7.8792|       Q|
|       0|     3|  male|null|    0|    0|  7.8958|       S|
|       0|     1|  male|40.0|    0|    0| 27.7208|       C|
|       1|     1|female|null|    1|    0|146.5208|       C|
|       1|     3|female|null|    0|    0|    7.75|       Q|
|       0|     2|  male|66.0|    0|    0|    10.5|       S|
|       0|     1|  male|28.0|    1|    0| 82.1708|       C|
|       0|     1|  male|42.0|    1|    0|    52.0|       S|
|       1|     3|  male|null|    0|    0|  7.2292|       C|
|       0|     3|  male|21.0|    0|    0|    8.05|       S|
|       0|     3|female|18.0|    2|    0|    18.0|       S|
|       1|     3|female|14.0|    1|    0| 11.2417|       C|
|       0|     3|female|40.0|    1|    0|   9.475|       S|
|       0|     2|female|27.0|    1|    0|    21.0|       S|
|       0|     3|  male|null|    0|    0|  7.8958|       C|
|       1|     2|female| 3.0|    1|    2| 41.5792|       C|
|       1|     3|female|19.0|    0|    0|  7.8792|       Q|
|       0|     3|  male|null|    0|    0|    8.05|       S|
|       0|     3|  male|null|    1|    0|    15.5|       Q|
|       1|     3|female|null|    0|    0|    7.75|       Q|
|       0|     3|  male|null|    2|    0| 21.6792|       C|
|       0|     3|female|18.0|    1|    0|    17.8|       S|
|       0|     3|  male| 7.0|    4|    1| 39.6875|       S|
|       0|     3|  male|21.0|    0|    0|     7.8|       S|
|       1|     1|female|49.0|    1|    0| 76.7292|       C|
|       1|     2|female|29.0|    1|    0|    26.0|       S|
|       0|     1|  male|65.0|    0|    1| 61.9792|       C|
|       1|     1|  male|null|    0|    0|    35.5|       S|
|       1|     2|female|21.0|    0|    0|    10.5|       S|
|       0|     3|  male|28.5|    0|    0|  7.2292|       C|
|       1|     2|female| 5.0|    1|    2|   27.75|       S|
|       0|     3|  male|11.0|    5|    2|    46.9|       S|
|       0|     3|  male|22.0|    0|    0|  7.2292|       C|
|       1|     1|female|38.0|    0|    0|    80.0|    null|
|       0|     1|  male|45.0|    1|    0|  83.475|       S|
|       0|     3|  male| 4.0|    3|    2|    27.9|       S|
|       0|     1|  male|null|    0|    0| 27.7208|       C|
|       1|     3|  male|null|    1|    1| 15.2458|       C|
|       1|     2|female|29.0|    0|    0|    10.5|       S|
|       0|     3|  male|19.0|    0|    0|  8.1583|       S|
|       1|     3|female|17.0|    4|    2|   7.925|       S|
|       0|     3|  male|26.0|    2|    0|  8.6625|       S|
|       0|     2|  male|32.0|    0|    0|    10.5|       S|
|       0|     3|female|16.0|    5|    2|    46.9|       S|
|       0|     2|  male|21.0|    0|    0|    73.5|       S|
|       0|     3|  male|26.0|    1|    0| 14.4542|       C|
|       1|     3|  male|32.0|    0|    0| 56.4958|       S|
|       0|     3|  male|25.0|    0|    0|    7.65|       S|
|       0|     3|  male|null|    0|    0|  7.8958|       S|
|       0|     3|  male|null|    0|    0|    8.05|       S|
|       1|     2|  male|0.83|    0|    2|    29.0|       S|
|       1|     3|female|30.0|    0|    0|  12.475|       S|
|       0|     3|  male|22.0|    0|    0|     9.0|       S|
|       1|     3|  male|29.0|    0|    0|     9.5|       S|
|       1|     3|female|null|    0|    0|  7.7875|       Q|
|       0|     1|  male|28.0|    0|    0|    47.1|       S|
|       1|     2|female|17.0|    0|    0|    10.5|       S|
|       1|     3|female|33.0|    3|    0|   15.85|       S|
|       0|     3|  male|16.0|    1|    3|  34.375|       S|
|       0|     3|  male|null|    0|    0|    8.05|       S|
|       1|     1|female|23.0|    3|    2|   263.0|       S|
|       0|     3|  male|24.0|    0|    0|    8.05|       S|
|       0|     3|  male|29.0|    0|    0|    8.05|       S|
|       0|     3|  male|20.0|    0|    0|  7.8542|       S|
|       0|     1|  male|46.0|    1|    0|  61.175|       S|
|       0|     3|  male|26.0|    1|    2|  20.575|       S|
|       0|     3|  male|59.0|    0|    0|    7.25|       S|
|       0|     3|  male|null|    0|    0|    8.05|       S|
|       0|     1|  male|71.0|    0|    0| 34.6542|       C|
|       1|     1|  male|23.0|    0|    1| 63.3583|       C|
|       1|     2|female|34.0|    0|    1|    23.0|       S|
|       0|     2|  male|34.0|    1|    0|    26.0|       S|
+--------+------+------+----+-----+-----+--------+--------+
only showing top 100 rows

### Missing Value 처리

In [10]:
df.describe().show()

+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|summary|           Survived|            Pclass|   Sex|               Age|             SibSp|              Parch|             Fare|Embarked|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|  count|                891|               891|   891|               714|               891|                891|              891|     889|
|   mean| 0.3838383838383838| 2.308641975308642|  null| 29.69911764705882|0.5230078563411896|0.38159371492704824| 32.2042079685746|    null|
| stddev|0.48659245426485753|0.8360712409770491|  null|14.526497332334035|1.1027434322934315| 0.8060572211299488|49.69342859718089|    null|
|    min|                  0|                 1|female|              0.42|                 0|                  0|              0.0|       C|
|    max|                  1|                 3|  male|              80.0|                 8|                  6|         512.3292|       S|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+

In [11]:
from pyspark.sql.functions import count

df.select([count(c) for c in df.columns]).show()

+---------------+-------------+----------+----------+------------+------------+-----------+---------------+
|count(Survived)|count(Pclass)|count(Sex)|count(Age)|count(SibSp)|count(Parch)|count(Fare)|count(Embarked)|
+---------------+-------------+----------+----------+------------+------------+-----------+---------------+
|            891|          891|       891|       714|         891|         891|        891|            889|
+---------------+-------------+----------+----------+------------+------------+-----------+---------------+

In [12]:
## 평균으로 Age의 null value 채우기
from pyspark.ml.feature import Imputer

imputer = Imputer(inputCols = ['Age'], outputCols = ['Age']).setStrategy('mean')  # Age가 null인 경우 평균으로 채움

df_cleaned = imputer.fit(df).transform(df)
df_cleaned.show(5)

+--------+------+------+----+-----+-----+-------+--------+
|Survived|Pclass|   Sex| Age|SibSp|Parch|   Fare|Embarked|
+--------+------+------+----+-----+-----+-------+--------+
|       0|     3|  male|22.0|    1|    0|   7.25|       S|
|       1|     1|female|38.0|    1|    0|71.2833|       C|
|       1|     3|female|26.0|    0|    0|  7.925|       S|
|       1|     1|female|35.0|    1|    0|   53.1|       S|
|       0|     3|  male|35.0|    0|    0|   8.05|       S|
+--------+------+------+----+-----+-----+-------+--------+
only showing top 5 rows

In [13]:
df_cleaned.describe().show()

+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|summary|           Survived|            Pclass|   Sex|               Age|             SibSp|              Parch|             Fare|Embarked|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|  count|                891|               891|   891|               891|               891|                891|              891|     889|
|   mean| 0.3838383838383838| 2.308641975308642|  null|29.699117647058763|0.5230078563411896|0.38159371492704824| 32.2042079685746|    null|
| stddev|0.48659245426485753|0.8360712409770491|  null|13.002015226002891|1.1027434322934315| 0.8060572211299488|49.69342859718089|    null|
|    min|                  0|                 1|female|              0.42|                 0|                  0|              0.0|       C|
|    max|                  1|                 3|  male|              80.0|                 8|                  6|         512.3292|       S|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+

In [14]:
## Embarked는 2개 밖에 안되므로 drop
df_cleaned = df_cleaned.na.drop(how='any')
df_cleaned.describe().show()

+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|summary|           Survived|            Pclass|   Sex|               Age|             SibSp|              Parch|             Fare|Embarked|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+
|  count|                889|               889|   889|               889|               889|                889|              889|     889|
|   mean|0.38245219347581555|2.3115860517435323|  null|29.653446370674192|0.5241844769403825|0.38245219347581555|32.09668087739029|    null|
| stddev|0.48625968831477334|0.8346997785705753|  null|12.968366309252314| 1.103704875596923| 0.8067607445174785|49.69750431670795|    null|
|    min|                  0|                 1|female|              0.42|                 0|                  0|              0.0|       C|
|    max|                  1|                 3|  male|              80.0|                 8|                  6|         512.3292|       S|
+-------+-------------------+------------------+------+------------------+------------------+-------------------+-----------------+--------+

In [15]:
df_cleaned.groupBy("Survived").count().show()
df_cleaned.groupBy("Pclass").count().show()
df_cleaned.groupBy("Sex").count().show()
df_cleaned.groupBy("Embarked").count().show()

+--------+-----+
|Survived|count|
+--------+-----+
|       1|  340|
|       0|  549|
+--------+-----+

+------+-----+
|Pclass|count|
+------+-----+
|     1|  214|
|     3|  491|
|     2|  184|
+------+-----+

+------+-----+
|   Sex|count|
+------+-----+
|female|  312|
|  male|  577|
+------+-----+

+--------+-----+
|Embarked|count|
+--------+-----+
|       Q|   77|
|       C|  168|
|       S|  644|
+--------+-----+

In [16]:
## category feature 변환
indexer = StringIndexer(inputCols=['Pclass', 'Sex', 'Embarked'], outputCols=['Pclass_', 'Sex_', 'Embarked_']).fit(df_cleaned)
df_r = indexer.transform(df_cleaned)
df_r.show(5)

+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+
|Survived|Pclass|   Sex| Age|SibSp|Parch|   Fare|Embarked|Pclass_|Sex_|Embarked_|
+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+
|       0|     3|  male|22.0|    1|    0|   7.25|       S|    0.0| 0.0|      0.0|
|       1|     1|female|38.0|    1|    0|71.2833|       C|    1.0| 1.0|      1.0|
|       1|     3|female|26.0|    0|    0|  7.925|       S|    0.0| 1.0|      0.0|
|       1|     1|female|35.0|    1|    0|   53.1|       S|    1.0| 1.0|      0.0|
|       0|     3|  male|35.0|    0|    0|   8.05|       S|    0.0| 0.0|      0.0|
+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+
only showing top 5 rows

In [17]:
## OneHot Encoding
ohe = OneHotEncoder(inputCols=['Pclass_', 'Sex_', 'Embarked_'], outputCols=['Pclass_ohe', 'Sex_ohe', 'Embarked_ohe']).fit(df_r)
df_ohe = ohe.transform(df_r)
df_ohe.show(5)

+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+
|Survived|Pclass|   Sex| Age|SibSp|Parch|   Fare|Embarked|Pclass_|Sex_|Embarked_|   Pclass_ohe|      Sex_ohe| Embarked_ohe|
+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+
|       0|     3|  male|22.0|    1|    0|   7.25|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|
|       1|     1|female|38.0|    1|    0|71.2833|       C|    1.0| 1.0|      1.0|(2,[1],[1.0])|    (1,[],[])|(2,[1],[1.0])|
|       1|     3|female|26.0|    0|    0|  7.925|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|
|       1|     1|female|35.0|    1|    0|   53.1|       S|    1.0| 1.0|      0.0|(2,[1],[1.0])|    (1,[],[])|(2,[0],[1.0])|
|       0|     3|  male|35.0|    0|    0|   8.05|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|
+--------+------+------+----+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+
only showing top 5 rows

In [18]:
print(df_ohe.columns)

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Pclass_', 'Sex_', 'Embarked_', 'Pclass_ohe', 'Sex_ohe', 'Embarked_ohe']

In [19]:
## Vector Feature
assembler = VectorAssembler(inputCols=["Age", "SibSp", "Parch", "Fare", "Pclass_ohe", "Sex_ohe", "Embarked_ohe"], outputCol="features")
output = assembler.transform(df_ohe)
output.show()

+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+--------------------+
|Survived|Pclass|   Sex|              Age|SibSp|Parch|   Fare|Embarked|Pclass_|Sex_|Embarked_|   Pclass_ohe|      Sex_ohe| Embarked_ohe|            features|
+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+--------------------+
|       0|     3|  male|             22.0|    1|    0|   7.25|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[22.0,1.0,0.0,7.2...|
|       1|     1|female|             38.0|    1|    0|71.2833|       C|    1.0| 1.0|      1.0|(2,[1],[1.0])|    (1,[],[])|(2,[1],[1.0])|[38.0,1.0,0.0,71....|
|       1|     3|female|             26.0|    0|    0|  7.925|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|(9,[0,3,4,7],[26....|
|       1|     1|female|             35.0|    1|    0|   53.1|       S|    1.0| 1.0|      0.0|(2,[1],[1.0])|    (1,[],[])|(2,[0],[1.0])|[35.0,1.0,0.0,53....|
|       0|     3|  male|             35.0|    0|    0|   8.05|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[35.0,0.0,0.0,8.0...|
|       0|     3|  male|29.69911764705882|    0|    0| 8.4583|       Q|    0.0| 0.0|      2.0|(2,[0],[1.0])|(1,[0],[1.0])|    (2,[],[])|(9,[0,3,4,6],[29....|
|       0|     1|  male|             54.0|    0|    0|51.8625|       S|    1.0| 0.0|      0.0|(2,[1],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[54.0,0.0,0.0,51....|
|       0|     3|  male|              2.0|    3|    1| 21.075|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[2.0,3.0,1.0,21.0...|
|       1|     3|female|             27.0|    0|    2|11.1333|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|[27.0,0.0,2.0,11....|
|       1|     2|female|             14.0|    1|    0|30.0708|       C|    2.0| 1.0|      1.0|    (2,[],[])|    (1,[],[])|(2,[1],[1.0])|(9,[0,1,3,8],[14....|
|       1|     3|female|              4.0|    1|    1|   16.7|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|[4.0,1.0,1.0,16.7...|
|       1|     1|female|             58.0|    0|    0|  26.55|       S|    1.0| 1.0|      0.0|(2,[1],[1.0])|    (1,[],[])|(2,[0],[1.0])|(9,[0,3,5,7],[58....|
|       0|     3|  male|             20.0|    0|    0|   8.05|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[20.0,0.0,0.0,8.0...|
|       0|     3|  male|             39.0|    1|    5| 31.275|       S|    0.0| 0.0|      0.0|(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[39.0,1.0,5.0,31....|
|       0|     3|female|             14.0|    0|    0| 7.8542|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|(9,[0,3,4,7],[14....|
|       1|     2|female|             55.0|    0|    0|   16.0|       S|    2.0| 1.0|      0.0|    (2,[],[])|    (1,[],[])|(2,[0],[1.0])|(9,[0,3,7],[55.0,...|
|       0|     3|  male|              2.0|    4|    1| 29.125|       Q|    0.0| 0.0|      2.0|(2,[0],[1.0])|(1,[0],[1.0])|    (2,[],[])|[2.0,4.0,1.0,29.1...|
|       1|     2|  male|29.69911764705882|    0|    0|   13.0|       S|    2.0| 0.0|      0.0|    (2,[],[])|(1,[0],[1.0])|(2,[0],[1.0])|(9,[0,3,6,7],[29....|
|       0|     3|female|             31.0|    1|    0|   18.0|       S|    0.0| 1.0|      0.0|(2,[0],[1.0])|    (1,[],[])|(2,[0],[1.0])|[31.0,1.0,0.0,18....|
|       1|     3|female|29.69911764705882|    0|    0|  7.225|       C|    0.0| 1.0|      1.0|(2,[0],[1.0])|    (1,[],[])|(2,[1],[1.0])|(9,[0,3,4,8],[29....|
+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+--------------------+
only showing top 20 rows

이제 모든 열이 단일 기능 벡터로 변환되었으므로 데이터를 표준화하여 비교 가능한 규모로 가져와야 합니다.

In [20]:
## Feature Scaling
from pyspark.ml.feature import StandardScaler

scaler = StandardScaler(inputCol='features', outputCol='standardized')
data_scaled = scaler.fit(output).transform(output)
data_scaled.show(truncate=False)

+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|Survived|Pclass|Sex   |Age              |SibSp|Parch|Fare   |Embarked|Pclass_|Sex_|Embarked_|Pclass_ohe   |Sex_ohe      |Embarked_ohe |features                                        |standardized                                                                                                                                 |
+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|0       |3     |male  |22.0             |1    |0    |7.25   |S       |0.0    |0.0 |0.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[22.0,1.0,0.0,7.25,1.0,0.0,1.0,1.0,0.0]         |[1.696435732564405,0.9060393064397433,0.0,0.14588257699617724,2.0099029206360277,0.0,2.094074651689162,2.2368218041444443,0.0]               |
|1       |1     |female|38.0             |1    |0    |71.2833|C       |1.0    |1.0 |1.0      |(2,[1],[1.0])|(1,[],[])    |(2,[1],[1.0])|[38.0,1.0,0.0,71.2833,0.0,1.0,0.0,0.0,1.0]      |[2.9302071744294267,0.9060393064397433,0.0,1.4343436552816002,0.0,2.337752823939248,0.0,0.0,2.55290756430783]                                |
|1       |3     |female|26.0             |0    |0    |7.925  |S       |0.0    |1.0 |0.0      |(2,[0],[1.0])|(1,[],[])    |(2,[0],[1.0])|(9,[0,3,4,7],[26.0,7.925,1.0,1.0])              |(9,[0,3,4,7],[2.0048785930306607,0.15946474795789028,2.0099029206360277,2.2368218041444443])                                                 |
|1       |1     |female|35.0             |1    |0    |53.1   |S       |1.0    |1.0 |0.0      |(2,[1],[1.0])|(1,[],[])    |(2,[0],[1.0])|[35.0,1.0,0.0,53.1,0.0,1.0,0.0,1.0,0.0]         |[2.698875029079735,0.9060393064397433,0.0,1.0684641156547603,0.0,2.337752823939248,0.0,2.2368218041444443,0.0]                               |
|0       |3     |male  |35.0             |0    |0    |8.05   |S       |0.0    |0.0 |0.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[35.0,0.0,0.0,8.05,1.0,0.0,1.0,1.0,0.0]         |[2.698875029079735,0.0,0.0,0.16197996480265198,2.0099029206360277,0.0,2.094074651689162,2.2368218041444443,0.0]                              |
|0       |3     |male  |29.69911764705882|0    |0    |8.4583 |Q       |0.0    |0.0 |2.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[],[])    |(9,[0,3,4,6],[29.69911764705882,8.4583,1.0,1.0])|(9,[0,3,4,6],[2.290120200095667,0.1701956691043815,2.0099029206360277,2.094074651689162])                                                    |
|0       |1     |male  |54.0             |0    |0    |51.8625|S       |1.0    |0.0 |0.0      |(2,[1],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[54.0,0.0,0.0,51.8625,0.0,1.0,1.0,1.0,0.0]      |[4.1639786162944485,0.0,0.0,1.0435634688916196,0.0,2.337752823939248,2.094074651689162,2.2368218041444443,0.0]                               |
|0       |3     |male  |2.0              |3    |1    |21.075 |S       |0.0    |0.0 |0.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[2.0,3.0,1.0,21.075,1.0,0.0,1.0,1.0,0.0]        |[0.15422143023312773,2.71811791931923,1.2395248613615906,0.42406556002681867,2.0099029206360277,0.0,2.094074651689162,2.2368218041444443,0.0]|
|1       |3     |female|27.0             |0    |2    |11.1333|S       |0.0    |1.0 |0.0      |(2,[0],[1.0])|(1,[],[])    |(2,[0],[1.0])|[27.0,0.0,2.0,11.1333,1.0,0.0,0.0,1.0,0.0]      |[2.0819893081472243,0.0,2.479049722723181,0.2240213095822814,2.0099029206360277,0.0,0.0,2.2368218041444443,0.0]                              |
|1       |2     |female|14.0             |1    |0    |30.0708|C       |2.0    |1.0 |1.0      |(2,[],[])    |(1,[],[])    |(2,[1],[1.0])|(9,[0,1,3,8],[14.0,1.0,30.0708,1.0])            |(9,[0,1,3,8],[1.0795500116318941,0.9060393064397433,0.6050766615636753,2.55290756430783])                                                    |
|1       |3     |female|4.0              |1    |1    |16.7   |S       |0.0    |1.0 |0.0      |(2,[0],[1.0])|(1,[],[])    |(2,[0],[1.0])|[4.0,1.0,1.0,16.7,1.0,0.0,0.0,1.0,0.0]          |[0.30844286046625546,0.9060393064397433,1.2395248613615906,0.33603297046016,2.0099029206360277,0.0,0.0,2.2368218041444443,0.0]               |
|1       |1     |female|58.0             |0    |0    |26.55  |S       |1.0    |1.0 |0.0      |(2,[1],[1.0])|(1,[],[])    |(2,[0],[1.0])|(9,[0,3,5,7],[58.0,26.55,1.0,1.0])              |(9,[0,3,5,7],[4.4724214767607045,0.5342320578273801,2.337752823939248,2.2368218041444443])                                                   |
|0       |3     |male  |20.0             |0    |0    |8.05   |S       |0.0    |0.0 |0.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[20.0,0.0,0.0,8.05,1.0,0.0,1.0,1.0,0.0]         |[1.5422143023312773,0.0,0.0,0.16197996480265198,2.0099029206360277,0.0,2.094074651689162,2.2368218041444443,0.0]                             |
|0       |3     |male  |39.0             |1    |5    |31.275 |S       |0.0    |0.0 |0.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[0],[1.0])|[39.0,1.0,5.0,31.275,1.0,0.0,1.0,1.0,0.0]       |[3.0073178895459907,0.9060393064397433,6.197624306807953,0.6293072545593714,2.0099029206360277,0.0,2.094074651689162,2.2368218041444443,0.0] |
|0       |3     |female|14.0             |0    |0    |7.8542 |S       |0.0    |1.0 |0.0      |(2,[0],[1.0])|(1,[],[])    |(2,[0],[1.0])|(9,[0,3,4,7],[14.0,7.8542,1.0,1.0])             |(9,[0,3,4,7],[1.0795500116318941,0.1580401291370173,2.0099029206360277,2.2368218041444443])                                                  |
|1       |2     |female|55.0             |0    |0    |16.0   |S       |2.0    |1.0 |0.0      |(2,[],[])    |(1,[],[])    |(2,[0],[1.0])|(9,[0,3,7],[55.0,16.0,1.0])                     |(9,[0,3,7],[4.241089331411013,0.3219477561294946,2.2368218041444443])                                                                        |
|0       |3     |male  |2.0              |4    |1    |29.125 |Q       |0.0    |0.0 |2.0      |(2,[0],[1.0])|(1,[0],[1.0])|(2,[],[])    |[2.0,4.0,1.0,29.125,1.0,0.0,1.0,0.0,0.0]        |[0.15422143023312773,3.624157225758973,1.2395248613615906,0.5860455248294707,2.0099029206360277,0.0,2.094074651689162,0.0,0.0]               |
|1       |2     |male  |29.69911764705882|0    |0    |13.0   |S       |2.0    |0.0 |0.0      |(2,[],[])    |(1,[0],[1.0])|(2,[0],[1.0])|(9,[0,3,6,7],[29.69911764705882,13.0,1.0,1.0])  |(9,[0,3,6,7],[2.290120200095667,0.2615825518552144,2.094074651689162,2.2368218041444443])                                                    |
|0       |3     |female|31.0             |1    |0    |18.0   |S       |0.0    |1.0 |0.0      |(2,[0],[1.0])|(1,[],[])    |(2,[0],[1.0])|[31.0,1.0,0.0,18.0,1.0,0.0,0.0,1.0,0.0]         |[2.3904321686134797,0.9060393064397433,0.0,0.36219122564568146,2.0099029206360277,0.0,0.0,2.2368218041444443,0.0]                            |
|1       |3     |female|29.69911764705882|0    |0    |7.225  |C       |0.0    |1.0 |1.0      |(2,[0],[1.0])|(1,[],[])    |(2,[1],[1.0])|(9,[0,3,4,8],[29.69911764705882,7.225,1.0,1.0]) |(9,[0,3,4,8],[2.290120200095667,0.14537953362722492,2.0099029206360277,2.55290756430783])                                                    |
+--------+------+------+-----------------+-----+-----+-------+--------+-------+----+---------+-------------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

In [21]:
data = data_scaled.select("standardized", "Survived")
data.show()

+--------------------+--------+
|        standardized|Survived|
+--------------------+--------+
|[1.69643573256440...|       0|
|[2.93020717442942...|       1|
|(9,[0,3,4,7],[2.0...|       1|
|[2.69887502907973...|       1|
|[2.69887502907973...|       0|
|(9,[0,3,4,6],[2.2...|       0|
|[4.16397861629444...|       0|
|[0.15422143023312...|       0|
|[2.08198930814722...|       1|
|(9,[0,1,3,8],[1.0...|       1|
|[0.30844286046625...|       1|
|(9,[0,3,5,7],[4.4...|       1|
|[1.54221430233127...|       0|
|[3.00731788954599...|       0|
|(9,[0,3,4,7],[1.0...|       0|
|(9,[0,3,7],[4.241...|       1|
|[0.15422143023312...|       0|
|(9,[0,3,6,7],[2.2...|       1|
|[2.39043216861347...|       0|
|(9,[0,3,4,8],[2.2...|       1|
+--------------------+--------+
only showing top 20 rows

In [22]:
## train/test split
train_data, test_data = data.randomSplit([0.75, 0.25])
train_data.count()

641

In [23]:
## ML model 작성
dt = DecisionTreeClassifier(featuresCol="standardized", labelCol="Survived", maxDepth=5, seed=42).fit(train_data)
rf = RandomForestClassifier(featuresCol="standardized", labelCol="Survived", numTrees=100, maxDepth=5, seed=42).fit(train_data)
gb = GBTClassifier(featuresCol="standardized", labelCol="Survived", seed=42).fit(train_data)

In [24]:
dt.getLabelCol(), rf.getLabelCol(), gb.getLabelCol()

('Survived', 'Survived', 'Survived')

In [25]:
## feature importance
print("DT", dt.featureImportances)
print("RF", rf.featureImportances)
print("GB", gb.featureImportances)

DT (9,[0,1,2,3,4,5,6,7,8],[0.08567902893811695,0.08508828854029611,0.0062655412994826855,0.08436488175774975,0.12781294932615211,0.05617436565841782,0.5268464437043068,0.014493345736582307,0.013275155038895411])
RF (9,[0,1,2,3,4,5,6,7,8],[0.10885924231236342,0.043486132053505114,0.0387866164917351,0.13976215618402094,0.1096005741487804,0.044472157414323414,0.465482234921467,0.024728615093611604,0.024822271380192905])
GB (9,[0,1,2,3,4,5,6,7,8],[0.27409346183687666,0.08553205507493501,0.03310392382131509,0.30749824355235356,0.05845230973700543,0.03914387379933416,0.16873740240393018,0.010960194078983182,0.022478535695266578])

In [26]:
## Predict on test dataset
pred_dt = dt.transform(test_data)
pred_rf = rf.transform(test_data)
pred_gb = gb.transform(test_data)
pred_dt.show(5)
pred_rf.show(5)
pred_gb.show(5)

+--------------------+--------+-------------+--------------------+----------+
|        standardized|Survived|rawPrediction|         probability|prediction|
+--------------------+--------+-------------+--------------------+----------+
|(9,[0,1,3,4],[2.2...|       1|  [10.0,30.0]|         [0.25,0.75]|       1.0|
|(9,[0,1,3,7],[1.4...|       1|  [5.0,107.0]|[0.04464285714285...|       1.0|
|(9,[0,1,3,8],[2.0...|       1|  [5.0,107.0]|[0.04464285714285...|       1.0|
|(9,[0,2,3,4],[2.2...|       0|  [10.0,30.0]|         [0.25,0.75]|       1.0|
|(9,[0,2,3,4],[3.0...|       0|   [14.0,1.0]|[0.93333333333333...|       0.0|
+--------------------+--------+-------------+--------------------+----------+
only showing top 5 rows

+--------------------+--------+--------------------+--------------------+----------+
|        standardized|Survived|       rawPrediction|         probability|prediction|
+--------------------+--------+--------------------+--------------------+----------+
|(9,[0,1,3,4],[2.2...|       1|[41.6755699793401...|[0.41675569979340...|       1.0|
|(9,[0,1,3,7],[1.4...|       1|[17.3751820826575...|[0.17375182082657...|       1.0|
|(9,[0,1,3,8],[2.0...|       1|[24.2826272567663...|[0.24282627256766...|       1.0|
|(9,[0,2,3,4],[2.2...|       0|[38.2830699463972...|[0.38283069946397...|       1.0|
|(9,[0,2,3,4],[3.0...|       0|[65.4465324493947...|[0.65446532449394...|       0.0|
+--------------------+--------+--------------------+--------------------+----------+
only showing top 5 rows

+--------------------+--------+--------------------+--------------------+----------+
|        standardized|Survived|       rawPrediction|         probability|prediction|
+--------------------+--------+--------------------+--------------------+----------+
|(9,[0,1,3,4],[2.2...|       1|[-0.3106745791426...|[0.34947466865944...|       1.0|
|(9,[0,1,3,7],[1.4...|       1|[-1.3487390381907...|[0.06312233311656...|       1.0|
|(9,[0,1,3,8],[2.0...|       1|[0.28799981754665...|[0.64014640390943...|       0.0|
|(9,[0,2,3,4],[2.2...|       0|[-0.5793414762374...|[0.23890668191983...|       1.0|
|(9,[0,2,3,4],[3.0...|       0|[1.24638940457154...|[0.92363403461878...|       0.0|
+--------------------+--------+--------------------+--------------------+----------+
only showing top 5 rows

In [27]:
from pyspark.ml.evaluation import BinaryClassificationEvaluator

dt_auc = BinaryClassificationEvaluator(labelCol="Survived").evaluate(pred_dt)
rf_auc = BinaryClassificationEvaluator(labelCol="Survived").evaluate(pred_rf)
gb_auc = BinaryClassificationEvaluator(labelCol="Survived").evaluate(pred_gb)

dt_auc, rf_auc, gb_auc

(0.7330337235228538, 0.8783444816053512, 0.8715510033444811)